Malayalam support added and multiple correction in 4 existing Indian languages
sutariyaraj/indic-num2words pull request #12
Opened 2024-07-05 12:25 UTC by debasish-mihup

1) Adds Malayalam language support
2) Multiple correct in 4 additional language - Hindi, Marathi, Telugu, Kannada

2024-07-05 12:57 UTC, raj-sutariya requested changes

2024-07-05 12:57 UTC, raj-sutariya commented on num_to_words/utils/constants.py
> +	"10,00000000": "ಶತಕೋಟಿ
no comma here please
```suggestion
	"1000000000": "ಶತಕೋಟಿ
```

2024-07-05 12:58 UTC, raj-sutariya commented
Thank you so much for adding malyalam support

2024-07-06 07:22 UTC, debasish-mihup commented
Added few missing quotes etc.

2024-07-08 07:56 UTC, raj-sutariya approved these changes

2024-07-08 07:56 UTC, merged

2024-07-13 14:42 UTC, amrzv commented on num_to_words/utils/constants.py
> +  "99": "निन्यान्बे",
What's the reason for introducing these breaking changes into this library?